### PR TITLE
check if derived mode is python mode

### LINKED ISSUE #558: elpy not working with django mode
i am trying [django-mode](http://melpa.org/#/django-mode). whenever i enable django mode, i am not able to enable elpy.  
when i am in *.py file, `elpy-mode` throws

    Elpy only works with `python-mode`

### PR DESCRIPTION
**Pull request by ChillarAnand**
closes #558

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
Awesome, thank you!

Could you use `derived-mode-p`? Think that would make the code more readable.

**Comment by ChillarAnand** [comment]
@jorgenschaefer  rectified that. thank you :smile:

**Comment by jorgenschaefer** [comment]
Looks good, thank you very much for the contribution!

**Comment by ChillarAnand** [comment]
Achievement unlocked :smile: 
First PR got merged into elpy. :dancers:

**Pull request merged**
