### PR TITLE
elpy-shell: removed setup functions, added documentation

### PR DESCRIPTION
**Pull request by rgemulla**
The ``elpy-use-ipython`` and ``elpy-use-cpython`` functions don't do anything particularly useful anymore now that Emacs 24.4 is required. The PR removes these functions but adds documentation for how to set up common environments. See also #1107.

### CODE REVIEW

**Comment by rgemulla** [comment]
Some test fail now because ``elpy-use-cpython`` is gone. My suggestion would be to simply remove this function anywhere in the tests (it doesn't do anything anymore). Before going ahead, I'd like to hear your thoughts on this though.

**Comment by rgemulla** [comment]
I had a quick look, it would actually suffice to remove ``elpy-use-cpython-test.el``.

**Comment by galaunay** [comment]
This seems fine to me.
Just by curiosity, have you any ideas why there is problem with ipython, but not with ipython in jupyter ?

**Comment by rgemulla** [comment]
No, I am not sure why.

**Comment by rgemulla** [comment]
@jorgenschaefer Are you also fine with removing both setup functions?

**Comment by jorgenschaefer** [comment]
Hm. I'm all in favor of doing this, though I think it would be nice to deprecate those functions with a reference to the documentation for a few versions, so people don't get too confused?

**Comment by rgemulla** [comment]
Yes, that's a good idea. One option would be to add the functions again; the only thing they do then is to throw an error with a reference to the documentation. Is this what you mean?

An alternative is to mark them obsolete, but I am not sure if elpy users would even realize.

**Comment by jorgenschaefer** [comment]
> One option would be to add the functions again; the only thing they do then is to throw an error with a reference to the documentation. Is this what you mean?

Yes, that's what I mean. Sorry for the confusion :-)

**Pull request merged**
