### PR TITLE
Add the possibility to display usages for thing at point

### PR DESCRIPTION
**Pull request by brotzeitmacher**
Got the idea from Improved M-. / M-, functionality #544

### CODE REVIEW

**Comment by TauPan** [comment]
Uhm, may I ask why this was apparently never merged? I notice that travis-ci is failing, so maybe that was the reason? Would be sweet to have this in elpy ;-}

I expected this to be in 1.19 because of @jorgenschaefer 's adding this to the 1.19 milestone, but it's not in the released code.

**Comment by brotzeit** [comment]
AFAIK elpy now works with `xref`. I'm not sure, but I think there was a PR some time ago. Take a look at `xref-find-references`.

**Comment by galaunay** [comment]
Xref commands should indeed work with Elpy.

`xref-find-references` can be quite slow sometimes, If you are just interested by the usages for the thing at point, you may want to use `(xref-find-references (elpy-xref--identifier-at-point))` instead.

**Comment by TauPan** [comment]
Hm, I guess I should re-read the documentation now and then ;) Thanks @brotzeit and @galaunay !

However this just returns references in the current buffer for me while e.g. elpy-rgrep-symbol returns quite a lot more (real references to the symbol in other python files, not just mentions of the string).

**Comment by brotzeit** [comment]
That doesn't sound very helpful indeed. I haven't used python for a while, but I know that emacs lsp support keeps getting better. Maybe you should give https://github.com/emacs-lsp/lsp-python a try. But I don't know the state of the python lsp server. I've only tried it with rust.

**Comment by galaunay** [comment]
The xref implementation uses jedi, so it should get references in other files as well (it does for me).

Python Language Server apparently uses jedi as well for references, so I would not expect fundamentally different results.

However, Xref implementation is new and has been a little bit chaotic (my bad).
There is certainly room for improvement.

**Pull request closed without merging**
