### PR TITLE
Add config option to disable backed error display

### LINKED ISSUE #763: Add config option to disable backend error displays entirely
I use python 3.4/3.5 for my projects (asyncio based).
Jedi raises exception on editing buffer with constructions like `yield from`, `async def`, `await` etc.

elpy reflects these errors by raising a buffer with bug report containing comprehensive report about the bug, but it's very annoying.

I use layout with two vertically separated buffers. As result the bug report appears in other (nonactive) buffer and focus is switched to it.

Is there an option to disable the annoying buffer flicker in case of Jedi errors?
I can live with partial autocomplete support.

Sorry, my knowledge of emacs list is close to zero and I have no time/intention to *contribute* into elpy and jedi. I just want to *use elpy with pleasure*.
So I just politely asking for elpy option which will make my life much easier.

### PR DESCRIPTION
**Pull request by ChillarAnand**
closes #763

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
Awesome. You're quick! Thank you :-)

**Comment by asvetlov** [comment]
@jorgenschaefer when do you expect publishing new release?

**Comment by jorgenschaefer** [comment]
@asvetlov, at the end of this month (there should be a new Elpy release every three months). :-)

**Comment by asvetlov** [comment]
sound good!
Thanks

**Pull request merged**
