### PR TITLE
Use custom symbol for regexp search

### LINKED ISSUE #574: Include html files while grepping?
While working on django projects, if user searches for variable `foo` only *.py files are grepped. 

For this we can use projectile-grep but it does fuzzy match and it is very slower.

Also if we want to rename a variable in a view and use multi edit, it wont edit variables in template files.

May be we can include *.html files?

### PR DESCRIPTION
**Pull request by ChillarAnand**
closes #574

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
Thanks for the contribution!

`elpy-rgrep-symbol` is a confusing name – what do you think about `elpy-rgrep-file-pattern` instead?
Also, could you be a bit more verbose in the commit message, explaining what this change is doing?

**Comment by ChillarAnand** [comment]
elpy-importmagic-fixup-test is failing on emacs 24.1. Dont know why.

**Comment by jorgenschaefer** [comment]
Hm. Temporary failure, apparently. That's weird. Flaky tests are annoying.

**Comment by jorgenschaefer** [comment]
Thanks again for the contribution!

**Pull request merged**
