### PR TITLE
Use popwin for docstring display if available.

### PR DESCRIPTION
**Pull request by birkenfeld**
Popwin is quite nice for such ephemeral windows. I don't know if that style of optional dependencies is ok with you though.

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
Good idea, I guess. What does popwin do special? :-)

Please make this an Elpy module (using the `global-init` and `global-stop` methods to set this up), so users can disable this behavior if they dislike it.

**Comment by birkenfeld** [comment]
`popwin` displays the buffer nicely in an unobtrusive way, and closes it automatically when it loses focus:

snap2

PS: The coveralls messages are getting a bit out of hand ;)

**Comment by jorgenschaefer** [comment]
Nice module.

I wonder why coveralls is going crazy. :-D Wonder if it's configurable.

**Comment by jorgenschaefer** [comment]
Note to self: This should be an elpy-module, not just global code.

**Comment by gopar** [comment]
@birkenfeld any interest in making this into a elpy-module ?
If not then will have to close. Thanks

**Comment by birkenfeld** [comment]
Sorry, no time ATM.

**Pull request closed without merging**
