### PR TITLE
Remove redundant flake8 checks for emacs >= 26.1

### LINKED ISSUE #1386: Unable to silence flymake
As is customary in my ipython config file I have a `get_config()` reference to a non imported symbol. This is not an error and I want to silence the linter using `# noqa`.

Now, this isn't working but I think it's because two different checkers are being run. `flake8` is indeed honouring `# noqa` but the second checker is not.

My supposition about the second checker is based on:

1. Without `#noqa` the error is reported twice, one of the reports include the flake8 code the other just the message.
2.  With `#noqa` the error is reported once without the flake8 code.
3. Style/convention warnings are completely suppresed by `#noqa`.

### PR DESCRIPTION
**Pull request by galaunay**
# PR Summary
Fix #1386.

For emacs >= 26.1, python.el supports flymake.

With both elpy and python.el performing the syntax check, we end up with redundant syntax check errors.

This commit removes a part of elpy's flymake module (only for emacs >= 26.1) to avoid
performing the syntax check twice.

# PR checklist

Please make sure that the following things have been addressed (and check the relevant checkboxes):

- [x] Commits respect our [guidelines](../CONTRIBUTING.rst)
- [x] Tests are passing properly (see [here](https://elpy.readthedocs.io/en/latest/extending.html#running-tests) on how to run Elpy's tests)
- [x] Code is not generating new bytecode warnings

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
You sometimes check for <= 26.1 and sometimes for < 26.1 – if that's not intentional, you could merge some of the checks to big when checks for easier reading. Otherwise, looks good to me!

**Comment by galaunay** [comment]
I tried to tidy up a bit and I added some comments for the distant futur when Elpy will stop supporting Emacs < 26.1.

Note to myself: need to check that it still works properly in Emacs < 26.1 before merging.

**Comment by galaunay** [comment]
It works properly for emacs 25.3 as well, merging.

**Comment by jorgenschaefer** [comment]
(Not specific to this PR, but just taking the opportunity here) – You are absolutely awesome. Thank you again for all your work. :-)

**Comment by galaunay** [comment]
Thanks, 
hope it helps :).

**Pull request merged**
