### PR TITLE
Add Green test runner

### PR DESCRIPTION
**Pull request by galaunay**
Add support for the [Green](https://github.com/CleanCut/green) test runner.
Following discussion #1222.

### CODE REVIEW

**Comment by galaunay** [comment]
Waiting for checks from @siwica.

**Comment by galaunay** [comment]
I added some tests for this new runner.
This is ready to merge.
@siwica, any feeback on this ?

**Comment by gopar** [comment]
I tested it, it works \o/

**Comment by galaunay** [comment]
Thanks, 
let's merge this.

**Pull request merged**
