### PR TITLE
Remove importmagic

### LINKED ISSUE #1230: Remove importmagic
importmagic creates a lot of problems because it tries to import all modules. Many modules do not know how to deal with this, and either emit spurious output, cause CPU hogging or even crash Python altogether.

As sad as it is, since importmagic adds some nice features, in the current state of affairs it's not a good solution. At the bare minimum, the suggestion for installation should be removed. Probably all code related to importmagic can be removed as well.

### PR DESCRIPTION
**Pull request by gopar**
Closes #1230

### CODE REVIEW

**Comment by gopar** [comment]
Yey, coverage increased \o/

**Comment by galaunay** [comment]
90% is a step, congratulation :).

I greped an occurrence of 'importmagic' in .travis.yml.
I suppose this can be safely removed as well.

**Comment by gopar** [comment]
Thanks. Weird, I was using projectile to grep through the project but that one never showed up

**Comment by gopar** [comment]
Something like `(make-obsolete 'importmagic-functions "support for importmagic has been dropped")`?

**Comment by galaunay** [comment]
Yes, I suppose.
At least for the interactive functions ?

**Comment by jorgenschaefer** [comment]
If you add compatibility functions, you can leave the keybindings there for a release or two. Otherwise, I would not bother with compatibility functions. It's just stuff to clean up later.

**Comment by gopar** [comment]
I added the keybindings back. So, now whether the user uses the keybindings or calls the function interactively, they should see the obsolete message

**Comment by galaunay** [comment]
Seems fine to me

**Comment by gopar** [comment]
Alright, if I get an additional thumbs up then I'll merge

**Comment by jorgenschaefer** [comment]
:+1:

**Comment by eb-enzo** [comment]
Thanks for your quick response. I'll take a look at `importmagic.el`. However, I mainly used `importsmagic` for imports ordering and formatting, not for resolving unknown symbols or adding new ones. Maybe I should search for a lightweight solution for my problem.
Thanks again.

**Comment by jorgenschaefer** [comment]
I can highly recommend [isort](https://pypi.python.org/pypi/isort) for that :-)

**Comment by eb-enzo** [comment]
EXACTLY what I need. Thanks so much.

**Pull request merged**
