### PR TITLE
Avoid-test-error-due-to-rpc-timeout

### PR DESCRIPTION
**Pull request by galaunay**
# PR Summary
`elpy-xref--references-test` have been producing random test errors in Travis (in #1341 at least).
As those errors only appear on Travis, this is a test PR to investigate this issue.

My first guess is that those errors are due to rpc timeout.
I increased the rpc timeout to see if travis is still failing or not.

# PR checklist

Please make sure that the following things have been addressed (and check the relevant checkboxes):

- [x] Commits respect our [guidelines](../CONTRIBUTING.rst)
- [x] Tests are passing properly (see [here](https://elpy.readthedocs.io/en/latest/extending.html#running-tests) on how to run Elpy's tests)
- [x] Code is not generating new bytecode warnings

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
Good guess :-)

**Comment by galaunay** [comment]
Now another test (`elpy-doc-should-find-documentation-from-inside-arguments`) is failing because of timeout.

Should we set `elpy-rpc-timeout` to an arbitrary big value for all tests ?

**Comment by jorgenschaefer** [comment]
Probably a good idea, if Travis has speed issues.

**Comment by galaunay** [comment]
Okay...
There was something else going wrong.

`elpy-xref--references-test` was failing for emacs 25.
It was not the last time the test was modified (#1258).

No idea why, but a simple `(save-buffer)` was enough to fix it.

**Pull request merged**
