### PR TITLE
test: Fix flake8 pip button test.

### PR DESCRIPTION
**Pull request by Apteryks**
Closes issue 1292 (see:
https://github.com/jorgenschaefer/elpy/issues/1292).

### CODE REVIEW

**Comment by galaunay** [comment]
Hi, 
thanks for the PR,

I agree with the `elpy-syntax-check-command` replacement.

However, tests are supposed to be run from within a virtual environment (see [CONTRIBUTING.rst](https://github.com/jorgenschaefer/elpy/blob/master/CONTRIBUTING.rst#setup)), and in this case, the "--user" part is not supposed to appear.

I will add a paragraph on testing Elpy in the docs, to make this clearer.

**Comment by Apteryks** [comment]
Hi,

Thanks for the prompt feedback. I've just packaged emacs-elpy for the GNU Guix package manager (http://gnu.org/s/guix/). I'm using Guix to provide the correct environment/dependencies rather than a virtualenv + pip, hence why I fall into this trap.

Granted this is not the 'typical' use case. If preferred I can keep the patch in the package definition as it is now:

``` scheme
(define-public emacs-elpy
  (package
    (name "emacs-elpy")
    (version "1.18.0")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/jorgenschaefer/elpy.git")
                    (commit version)))
              (file-name (string-append name "-" version "-checkout"))
              (sha256
               (base32
                "17iwdaly9kw17ih86rk9w1iswn8r6vvj9sh71picsxg6gqdrqnrk"))))
    (build-system emacs-build-system)
    (arguments
     `(#:phases
       (modify-phases %standard-phases
         ;; Workaround for issue #1285 (see:
         ;; https://github.com/jorgenschaefer/elpy/issues/1285).
         (add-after 'unpack 'fix-elpy-shell.el
           (lambda _
             (substitute* "elpy-shell.el"
               ((";;; User customization")
                (string-append ";;; User customization\n\n"
                               "(eval-when-compile (require 'subr-x))")))))
         ;; test-helper.el overrides PYTHONPATH, but Guix depends on it to
         ;; find its Python libraries.
         (add-after 'unpack 'fix-python-path
           (lambda _
             (substitute* "test/test-helper.el"
               (("format \"PYTHONPATH=%s\" elpy-dir")
                "format \"PYTHONPATH=%s:%s\" elpy-dir (getenv \"PYTHONPATH\")"))))
         ;; Fix submitted upstream (see:
         ;; https://github.com/jorgenschaefer/elpy/pull/1293).
         (add-after 'unpack 'fix-broken-test
           (lambda _
             (substitute* "test/elpy-config-test.el"
               (("python-check-command") "elpy-syntax-check-command")
               (("python -m pip install flake8")
                "python -m pip install --user flake8")))))
       #:tests? #t
       #:test-command ("ert-runner")))
    (propagated-inputs
     `(("emacs-company" ,emacs-company)
       ("emacs-f" ,emacs-f)
       ("emacs-find-file-in-project" ,emacs-find-file-in-project)
       ("emacs-highlight-indentation" ,emacs-highlight-indentation)
       ("emacs-yasnippet" ,emacs-yasnippet)
       ("pyvenv" ,emacs-pyvenv)
       ("s" ,emacs-s)))
    (native-inputs
     `(("ert-runner" ,ert-runner)
       ("python" ,python-wrapper)
       ("python-autopep8" ,python-autopep8)
       ("python-flake8" ,python-flake8)
       ("python-jedi" ,python-jedi)
       ("python-yapf" ,python-yapf)))
    (home-page "https://github.com/jorgenschaefer/elpy")
    (synopsis "Python development environment for Emacs")
    (description "Elpy brings powerful Python editing to Emacs.  It combines
and configures a number of other packages written in Emacs Lisp as well
as Python.")
    (license license:gpl3+)))
```

**Comment by galaunay** [comment]
I understand better why you have found some well hidden bugs.
Thanks for packaging Elpy to Guix.

I am not very familiar with Guix package manager, 
is there not any way of using a virtualenv to run the tests ?

btw: issue @1285 should be fixed now.

**Comment by Apteryks** [comment]
I've founded an OK workaround to use with Guix:
``` scheme
         (add-before 'check 'fake-virtualenv
           (lambda _
             (setenv "VIRTUAL_ENV" "/tmp")))
```
I'm just tricking Elpy into thinking I'm using a virtualenv while I'm not. Good enough for me. I'm closing the PR.

**Pull request closed without merging**
