### PR TITLE
Make snippets able to handle arguments with type annotations.

### PR DESCRIPTION
**Pull request by galaunay**
# PR Summary
Follow discussion in #1246.

Make snippets (notably `__init__`) able to handle arguments with type annotations.

`elpy-snippet-split-args` now uses regular expressions to extract argument name (instead of using `split-string`).

# PR checklist

Please make sure that the following things have been addressed (and check the relevant checkboxes):

- [x] Commits respect our [guidelines](../CONTRIBUTING.rst)
- [x] Tests are passing properly (see [here](https://elpy.readthedocs.io/en/latest/extending.html#running-tests) on how to run Elpy's tests)
- [x] Code is not generating new bytecode warnings

### CODE REVIEW

**Comment by galaunay** [comment]
Added tests to be sure everything works fine.

**Comment by jorgenschaefer** [comment]
I like it. Does this interact with the attempts to merge the snippets into yasnippets? https://github.com/AndreaCrotti/yasnippet-snippets/pull/259

**Comment by galaunay** [comment]
Yes it does :).

@sten0 do you think this can be integrated in the yasnippets PR ?

**Comment by sten0** [comment]
@galaunay 1ad8dc56f2a2ee37cbbd7b421e7a380fa8cd4dda definitely can be.  If you want to add it to the yasnippets PR and want all the glory, then please fork my fork, apply your patch to the tip of the merge-elpy-snippets-WIP branch, and submit a pull request.  https://github.com/sten0/yasnippet-snippets/tree/merge-elpy-snippets-WIP  I'd prefer not to do this work myself ;-)  but I'd be happy to if you insist.

Do the tests actually depend on elpy-mode?  If not then I think it would be really cool to add them to yasnippet-snippets, because I think your work could inspire others to write more powerful snipppets and self-tests.  Yasnippet-snippets doesn't have any self-tests of its own yet, so I see it as an opportunity to lead by example.

**Comment by gopar** [comment]
Looks like the merge for yasnippets didn't happen? :(

**Comment by galaunay** [comment]
This has been delayed because all the snippets were supposed to be merged into yasnippet.
Until they are indeed merged, they will be available in Elpy.

**Comment by sten0** [comment]
@galaunay, thank you for your work on this, and sorry I forgot about it.  165c72d will make the next attempt much faster.  At the moment I'm focused on getting through my back-queue before the upcoming Debian freeze, plus bumping the urgency for QA work.

**Pull request merged**
