### PR TITLE
Fix #1945

### LINKED ISSUE #1945: elpy unable to find the installed packages and RPC update.
# Summary
My Elpy was working properly but then I update my distro to the latest release and suddenly everything broke. I reinstalled elpy, emacs as well as all the packages rope, flake8, autopep8, jedi. However my `elpy-config` is still not able to find them. Even when I install these packages from the `elpy-config` it is unable to find them

# Steps to reproduce
Recently Update my Fedora Linux Distro from 33 to 35

# My configuration
## Emacs = 27.2

# My `pip list` output
```
autopep8           1.6.0
black              21.10b0
flake8             4.0.1
jedi               0.18.0
mypy               0.910
mypy-extensions    0.4.3
yapf               0.31.0

```

## Result of `(elpy-config)`
```
Elpy Configuration

Emacs.............: 27.2
Elpy..............: Not found (Python), 1.35.0 (Emacs Lisp)
Virtualenv........: None
Interactive Python: jupyter ... (/usr/local/bin/jupyter)
RPC virtualenv....: rpc-venv (/home/sbn/.emacs.d/elpy/rpc-venv)
 Python...........: /usr/bin/python3.10 nil (/usr/bin/python3.10)
 Jedi.............: Not found
 Autopep8.........: Not found
 Yapf.............: Not found
 Black............: Not found
Syntax checker....: flake8 (/usr/local/bin/flake8)

Warnings

You have not activated a virtual env. It is not mandatory but often a
good idea to work inside a virtual env. You can use `M-x
pyvenv-activate` or `M-x pyvenv-workon` to activate one.

The Python interpreter could not find the elpy module. Please report
to: https://github.com/jorgenschaefer/elpy/issues/new.

There was an unexpected problem starting the RPC process. Please check
the following output to see if this makes sense to you. To me, it
doesn't.

<string>:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
{"can_connect_to_pypi": true, "rpc_python_version": "3.10.0", "elpy_version": "1.35.0", "jedi_version": "0.18.0", "jedi_latest": null, "autopep8_version": "1.6.0", "autopep8_latest": null, "yapf_version": "0.31.0", "yapf_latest": null, "black_version": "21.10b0", "black_latest": null}

Elpy could not connect to Pypi (or at least not quickly enough) and
check if the python packages were up-to-date. You can still try to
update all of them:

[Update python packages]

The Jedi package is not currently installed. This package is needed
for code completion, code navigation and access to documentation.

[Install jedi]

No autoformatting package is currently installed. At least one is
needed (Autopep8, Yapf or Black) to perform autoformatting (`C-c C-r
f` in a python buffer).

[Install autopep8]
[Install yapf]
[Install black]


```

## Elpy configuration in my init.el
```
;; Python Configurations
(elpy-enable)
(setq python-shell-interpreter "jupyter"
      python-shell-interpreter-args "console --simple-prompt"
      python-shell-prompt-detect-failure-warning nil)
(add-to-list 'python-shell-completion-native-disabled-interpreters
             "jupyter")

```

### PR DESCRIPTION
**Pull request by etermory**
# PR Summary
Fix #1945

# PR checklist

Please make sure that the following things have been addressed (and check the relevant checkboxes):

- [x] Commits respect our [guidelines](../CONTRIBUTING.rst)
- [x] Tests are passing properly (see [here](https://elpy.readthedocs.io/en/latest/extending.html#running-tests) on how to run Elpy's tests)

### CODE REVIEW

**Comment by gopar** [comment]
LGTM.
Merging!

**Review by gopar — APPROVED** [review]

**Comment by etermory** [comment]
I don't know why python tests failed.
I just modified the ".el" file.

**Comment by gopar** [comment]
Hmm I'll investigate some time this week why its failing but I believe that tests have been flaky for some time.

**Comment by gopar** [comment]
Merged. Thank You!

**Pull request merged**
