### PR TITLE
Add support for emacs 24.3

### PR DESCRIPTION
**Pull request by galaunay**
# PR Summary
Follow #1431.

Add back support for Emacs 24.3, as proposed by @CdeMills.

@jorgenschaefer I don't like the idea of complexifying the code either, but this is apparently useful for some users.
Let to discuss if we want to merge this into the main branch, or instead to make a backport branch.

# PR checklist

Please make sure that the following things have been addressed (and check the relevant checkboxes):

- [x] Commits respect our [guidelines](../CONTRIBUTING.rst)
- [ ] Tests are passing properly (see [here](https://elpy.readthedocs.io/en/latest/extending.html#running-tests) on how to run Elpy's tests)
- [x] Code is not generating new bytecode warnings

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
I'm still confused why @CdeMills can't just upgrade their Emacs? We do not support Python 2.5, either, for example.

Can't this be solved by some gist with an .el file that users with utterly outdated Emacs can use?

**Comment by CdeMills** [comment]
Hello,

For years, I was under Fedora. This means, every 6 month, the same circus.
New version going out, read the doc, find how to upgrade from n to n+1
without reinstalling, try it, understand why it fails (the reason is
different at each new version), and so on.

CentOS offers a much more stable experience. You have small updates which
never break any compatibility rule. The drawback is, as you mention, that
most of the software can be seen as ... outdated.

I compiled Emacs 26.6 using the Linux From Scratch approach. It runs ...
but I get from time to time segmentation faults. I don't have the time to
dig and understand why. So getting elpy working in conjunction with
Emacs-24.3 is the shortest path, with the added benefit that all peoples
under Redhat / CentOS / Scientific Linux could use it.

Regards

Pascal


Le ven. 31 août 2018 à 10:20, Jorgen Schäfer <notifications@github.com> a
écrit :

**Comment by jorgenschaefer** [comment]
Might I suggest using an older version of Elpy, then?

**Comment by CdeMills** [comment]
Hello,

why not ? What is the latest elpy compatible with 24.3 ? How to install it
from package manager ?

Regards

Pascal

Le ven. 31 août 2018 à 11:19, Jorgen Schäfer <notifications@github.com> a
écrit :

**Comment by jorgenschaefer** [comment]
Emacs' package management system only supports installing the latest version, so you have to use the git repo. You can try the commit `f6a8ac01f0fa191e6f09547fa77d017004fe7b45`. If that does not work, try `1c21d9f8fb8ad8020c60f165ced1ccb753a9ca55`.

**Comment by galaunay** [comment]
This is a duplicate of #1448.
I am closing this.

**Pull request closed without merging**
