### PR TITLE
Restart rpc process when virtualenv is activated

### LINKED ISSUE #663: Restart rpc after changing venv
It is better if elpy can restart rpc automatically after changing a virtualenv.

### PR DESCRIPTION
**Pull request by ChillarAnand**
closes #663

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
Thanks :-) `elpy-rpc--buffer` is a buffer-local variable, and `pyvenv-post-activate-hooks` is not run in any specific buffer, so you will need to find Elpy buffers to reset that variable in them.

Also, the `add-hook` call should be in `elpy-enable`, not at the top level.

**Comment by ChillarAnand** [comment]
Wouldn't it be  easier if directly call `elpy-rpc-restart`?

**Comment by jorgenschaefer** [comment]
> Wouldn't it be easier if directly call `elpy-rpc-restart`?

Depends. `elpy-rpc-restart` would kill all existing RPC processes. Do we want to keep the old RPC process around in case we switch back to the old virtualenv (e.g. using pyvenv's tracking mode), or do we want to re-start them every time, possibly causing delays with importmagic's loader?

**Comment by ChillarAnand** [comment]
I didn't know about that. Updated :-)

**Comment by jorgenschaefer** [comment]
Excellent, thank you!

**Pull request merged**
