### PR TITLE
minor typo and style fixes

### PR DESCRIPTION
**Pull request by sten0**
# PR Summary
Just some very minor fixes `lintian` complained about when I prepared 1.35.0 for Debian.  P.S. Our deadline for importing new features and new releases is early February.  After that I can only cherry pick fixes.

# PR checklist

Please make sure that the following things have been addressed (and check the relevant checkboxes):

- [x] Commits respect our [guidelines](../CONTRIBUTING.rst)
- [ ] Tests are passing properly (see [here](https://elpy.readthedocs.io/en/latest/extending.html#running-tests) on how to run Elpy's tests)

## For new features only:
- [ ] Tests has been added to cover the change
- [x] The documentation has been updated

### CODE REVIEW

**Comment by gopar** [comment]
Oh no, you've broken all our tests 😉

@galaunay I looked at the yaml file but couldn't see anything that stood out as to why CI is failing. (Also I don't have any experience with using the CI that github provides)

I'm OK with merging this in (as it is only text changes).

**Comment by sten0** [comment]
> Oh no, you've broken all our tests 
> 

Oh my haha :-p

> @galaunay I looked at the yaml file but couldn't see anything that stood out as to why CI is failing. (Also I don't have any experience with using the CI that github provides)
> 

I took a look at the logs for build "27.1, 3.8" build, and believe that the same problem is affecting all of them.  It looks like an infrastructure change to me, and the relevant doc is at https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/  It looks like "plan to fully disable them in the future" means about a month.

> I'm OK with merging this in (as it is only text changes).

Thanks :-)

**Comment by sten0** [comment]
@gopar, it seems I missed one.  I made a fixup commit, squashed, and force pushed.  Now fixed :-)

**Comment by gopar** [comment]
Hey @sten0 
Let me know if you'd like to make some more changes, otherwise i'll merge this in since it's just text.

Thanks!

**Comment by sten0** [comment]
Hi Daniel,

Daniel Gopar <notifications@github.com> writes:

> Hey @sten0 
> Let me know if you'd like to make some more changes, otherwise i'll merge this in since it's just text.
>

I believe I've found everything user-facing that needs to be fixed, so
please go ahead and merge.

If you also care about typos in comments, then there is also this:

index b7d7a05..3dedc6f 100644
--- a/elpy/jedibackend.py
+++ b/elpy/jedibackend.py
@@ -283,7 +283,7 @@ class JediBackend(object):
         if not call:
             return None
         # Strip 'param' added by jedi at the beginning of
-        # parameter names. Should be unecessary for jedi > 0.13.0
+        # parameter names. Should be unnecessary for jedi > 0.13.0
         params = [re.sub("^param ", '', param.description)
                   for param in call.params]
         return {"name": call.name,

> Thanks!
>

You're welcome, it's just a little thing. ;-) I wish I had the free time
to figure out #1856 ...

Cheers,
Nicholas

**Pull request merged**
