### PR TITLE
some commits I made to the importmagic branch but never pushed

### PR DESCRIPTION
**Pull request by birkenfeld**

### CODE REVIEW

**Comment by birkenfeld** [comment]
Hm. Not sure why the seemingly unrelated iblock test starts failing...

**Comment by jorgenschaefer** [comment]
Looks like d43de7a – I have no idea why that suddenly started to happen, really weird. Try rebasing ontop of master to get some bug fixes.

**Comment by birkenfeld** [comment]
ok, merged in master. seems to fix it.

**Comment by jorgenschaefer** [comment]
Merged into master. Thank you very much for all the work!

**Pull request closed without merging**
