### PR TITLE
One-line python requirements install line added

### PR DESCRIPTION
**Pull request by Thalmann**
When i was installing elpy i was missing this - i find it easier to copy the line than typing it all out or getting the repo and installing via the requirements file :)
Up to you ofc.

### CODE REVIEW

**Comment by gopar** [comment]
Shouldn't `pip3` just be `pip`? Since people might want to use Elpy for py2 dev and not py3. Also, if you're in a virtual env then doing pip3 might be install packages to the global system python instead of your virtual one.

`sudo` might also be a little extra since not everyone is in a linux machine (Windows) and can confuse people (beginners), plus some people might not have sudo powers and just install in user directory.

Best to keep it generic but this is just my point of view. Up to @jorgenschaefer

**Comment by Thalmann** [comment]
I totally agree with you, i thought it was only python 3 for some reason :)

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the contribution! I like this! Could you remove `rope` and `yapf` (they do the same thing as `jedi` and `autopep8`) and squash the commits into one? I'll be happy to merge then :-)

**Comment by Thalmann** [comment]
Fixed here: https://github.com/jorgenschaefer/elpy/pull/982

**Pull request closed without merging**
