### PR TITLE
Add emacs 26.1 to travis

### PR DESCRIPTION
**Pull request by galaunay**
# PR Summary
Just add emacs 26.1 to travis.

### CODE REVIEW

**Comment by galaunay** [comment]
Travis raises a bug during cask install for emacs 26.1.
It is apparently related to [this issue](https://github.com/cask/cask/issues/367) in cask.

A guy in [flycheck](https://github.com/flycheck/flycheck/commit/4f5eba0c9bb0a8487c6a8670506af122cdd98700) fixed this by adding `--verbose` to `cask` call.
And it's working...

**Comment by galaunay** [comment]
I have trouble fixing `elpy-flymake-show-error`...

Apparently `(fboundp 'flymake-diagnostics))` in `elpy-flymake-error-at-point` return nil if `flymake-diagnostics` is overwritten with `mltef*`.

**Comment by jorgenschaefer** [comment]
Looks like it is working, you are just checking for `test-error-1, test-error-2` but your mock function returns `error description`?

**Comment by galaunay** [comment]
I have a different error locally.
It appears that I forgot to include the last commit modifying flymake integration...

There was still some tests to fix following the merging of #1387.

**Pull request merged**
