### PR TITLE
Add `elpy-test-do-at-point-p`

### LINKED ISSUE #624: elpy-test-at-point is too restrictive about test file names
This condition is used to determine whether elpy-test-at-point should return test information

``` elisp
(if (and file (string-match "/test[^/]*$" file))
```

Some python libraries do not use this naming convention for test files. Is this logic even all that necessary. It seems like it should be enough if the function in close proximity has a 'test' name.

If you think that keeping this is absolutely necessary I would at least recommend that it be moved into a function that is configurable by the user.

something like `elpy-test--is-test-file-function`

I can make this change if it sounds good to you.

### PR DESCRIPTION
**Pull request by IvanMalison**
This variable will control when at point information should
be used for running individual tests. Fixes #624.

### CODE REVIEW

**Comment by IvanMalison** [comment]
I did what I suggested in #624 but after I thought about it a bit, I decided that it might make sense to restrict when this happens or how exactly it happens. What happens if you are in a setup method for a test class. With this pull request, the runner would attempt to run the test class . the setup method which would likely result in no tests being executed. Perhaps there should be a transformation step on the test name? I guess the individual runners could handle this? It's hard to support all these different test runners in a generic way :(

**Comment by jorgenschaefer** [comment]
Thank you for the contribution!

When do you think a user would seriously change the value of that option from the default? Considering the default heuristic is easily circumvented – use a prefix argument or just go to the start/end of the buffer before hitting `C-c C-t` – the extra option seems a bit superfluous.

Do you yourself have a need for such an option?

**Comment by IvanMalison** [comment]
> When do you think a user would seriously change the value of that option from the default?

I doubt they would. I only added it in case someone preferred the old behavior.

**Comment by IvanMalison** [comment]
Looks like the tests failed, which is strange because I ran them locally and they passed. Maybe it has to do with version?

**Comment by IvanMalison** [comment]
ah yeah looks like they fail for 24.1 and 24.2. Interesting. Will investigate.

**Comment by jorgenschaefer** [comment]
> I doubt they would. I only added it in case someone preferred the old behavior.

Leave it out, then. I like the new behavior you suggested. :-)

**Comment by jorgenschaefer** [comment]
Any updates on this code? The tests are failing, and I think the simplification we talked about above would be nice :-)

**Comment by IvanMalison** [comment]
I'll try to look this weekend

**Comment by jorgenschaefer** [comment]
Hello! Any updates on this?

**Comment by gopar** [comment]
Update?

**Comment by gopar** [comment]
Over 2 years with no updates. Closing this

**Pull request closed without merging**
