### PR TITLE
Source yapf style file from elpy-project-root or default-directory.

### PR DESCRIPTION
**Pull request by jonmoore**
The suggestion is to do this rather than using os.getcwd(), which does not pick up project-specific  yapf style settings, similarly to #971 for importmagic.

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the contribution! This looks very good. Do you think there could be tests for this functionality, especially for the Python side?

In any case, could you squash the commits? I'll be happy to merge. :-)

**Comment by landakram** [comment]
@jorgenschaefer GitHub now lets folks squash commits on PR merge. Given that, can you merge it and squash when you merge? Otherwise, let's hope @jonmoore sees this :)

Signed, someone who benefits from this PR

**Comment by galaunay** [comment]
I can add tests for this, 
but after taking a look at the yapf documentation, it says:
>   --style STYLE         
specify formatting style: either a style name (for
example "pep8" or "google"), or the name of a file
with style settings. The default is pep8 unless a
.style.yapf or setup.cfg file located **in one of the
parent directories of the source file** (or current
 directory for stdin)

So is this really necessary, as yapf should already pick up the style file present in the project root directory ?

**Comment by d8660091** [comment]
@galaunay Nope. I ran into this problem the other day. It turns out that elpy tries to pick up styles at my root directory '/' in my machine. I know it's caused by os.getcwd() but I didn't figured out how cwd is set to '/'.

**Comment by galaunay** [comment]
@d8660091 I see it now.
yapf is called from the rpc, for which the current directory is `/`.

I just tested and took a look at the PR, it seems fine.
However, It may worth indicating somewhere that Elpy is now looking for yapf style file in the project root.

I will try to add this and merge the PR in the following days.

**Comment by jorgenschaefer** [comment]
You people are all awesome. That is all. :-D

**Comment by galaunay** [comment]
I made another PR for that.
Closing this one !

**Pull request closed without merging**
