### PR TITLE
Add debugging functions.

### PR DESCRIPTION
**Pull request by ionrock**
This will run pdb, set a break point and clear all the breakpoints.

I haven't set any keybindings or implemented a history look up as it seems worthwhile to see if this is something others use. 

Let me know what should be changed / updated. Also, if this is OK to merge but you'd like to see some feature added, please feel free to give me a ticket. 

Thanks for taking a look!

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
I am sorry for having left this lying around for so long without any further response.

First of all, again, thank you for the contribution. Sadly, I am unsure what to do with it, exactly. And I do feel bad for taking so long only to come up with a mostly-negative response.

There are three commands in this patch.

The first one is a command to run the current file under a debugger. This is useful, but I am not sure if this is a good implementation. Quite regularly, I am working in a module somewhere. To run this under a debugger, I need to run the _main program_ under pdb, not the current module. Elpy currently lacks a way of specifying this main program. So this command would, for the most part, not add anything over `pdb` for me. So I am unsure if I want to include it as is.

In my little imaginary world, `elpy-debug` would run "the current program" under pdb. This would require a way of specifying "the current program". Then we could also have a command that simply _executes_ the "current program", instead of running it under a debugger. I am unsure how to do this well, or how the interface for specifying "the current program" would look like. Many projects have more than one, so it would require some sort of election. Tricky!

The second command adds a pdb breakpoint at point. This is currently handled by yasnippet simply by typing `pdb<TAB>` anywhere in the buffer. I do not think a command would simplify this much.

Leaves the command to remove pdb lines. I like that, actually. Can you think of a good key binding for this? `C-c C-b r` might work, with `C-c C-b` a general debugging prefix?

**Comment by ionrock** [comment]
No worries! I forgot I submitted this :)

I sat with this for a little while and came to a similar conclusion. It was difficult to use it consistently.

The `C-c C-b` seems fine to me. That said, if you choose to skip it completely, that is OK too. Thanks for taking a look!

**Comment by whirm** [comment]
What about integrating something like realgud? https://github.com/rocky/emacs-dbgr (which supports setting breakpoints without having to modify the source code and other cool stuff) and using a dir-local to store the different execution profiles?

**Comment by birkenfeld** [comment]
As I said in https://github.com/jorgenschaefer/elpy/issues/357 I tested it in September and thought emacs-dbgr is not ready yet.  But it seems to be actively developed, so it'll have to be checked again.

**Comment by whirm** [comment]
Oh, I had completely forgot about that, sorry :D

**Comment by jorgenschaefer** [comment]
Hm. I keep pushing this forward. I don't think this is useful enough to be included in Elpy, so I will simply close this. Despite of this, I do greatly appreciate the suggestion!

**Pull request closed without merging**
