### PR TITLE
Remove Rope IDE features

### PR DESCRIPTION
**Pull request by galaunay**
Following discussion in #1243.
Remove Rope IDE features and make Jedi backend the default one.

### CODE REVIEW

**Comment by gopar** [comment]
Sweeeet, Can you resolve the conflict? Wanna see the tests run :P

**Comment by galaunay** [comment]
Some rebase later... :)
I think it's good, but it's a bit tricky because half the rope-related stuff need to be preserved for refactoring functions.

**Comment by jorgenschaefer** [comment]
lgtm, thank you very much! The whole backend code and the tests can likely be simplified a lot after this. And I guess the "native" backend can go away as well and elpy will just not provide completion without jedi, simplifying the code even further. (Not necessarily in this PR, but it's something that can be done in the future :-) )

**Comment by galaunay** [comment]
Great ideas, I will try to clean all of this a little in the following days.

**Comment by galaunay** [comment]
Made my best.
I assume the code might still be simplified in 'server.py', but I am unsure how.
If someone has some insight on this...

**Comment by jorgenschaefer** [comment]
We can also simplify more later. Do not hesitate to merge if it works. :-)

**Comment by galaunay** [comment]
Noted.
600 lines less is still a good start :)

**Pull request merged**
