### PR TITLE
Added support for autopep8

### PR DESCRIPTION
**Pull request by ChillarAnand**
Automatically format code to PEP8 style using autopep8.
If a region is selected format only that region else format entire buffer.

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
Thank you! You can `git push --force` to override a previous pull request, no need to close and re-open.

There should be no merge commit in this branch anymore. Could you rebase again, please?

**Comment by ChillarAnand** [comment]
Sorry. You already [told me about that](https://github.com/jorgenschaefer/elpy/pull/540#issuecomment-94498371). I accidentally deleted a branch and done push force so it was closed automatically. 

Updated now :-)

**Comment by jorgenschaefer** [comment]
Thanks!

Did I also already ask why you removed `-Qwarnall` from the test runner? :-)

Also, I think this is not using your `interactive c` code anymore? Any reason?

**Comment by ChillarAnand** [comment]
> Did I also already ask why you removed -Qwarnall from the test runner? :-)

Python3 doesnt support it.

> Also, I think this is not using your interactive c code anymore?

Looks like haven't picked a commit. Will update it.

**Comment by jorgenschaefer** [comment]
> Python3 doesnt support it.

Oh, right. At the risk of annoying you, could you extract that specific change into a separate commit with an explanatory commit message for this? It has nothing to do with the rest of the changes, and it'd be a good idea to be able to figure out later why it was removed. Thank you!

**Comment by ChillarAnand** [comment]
Separated it.

**Comment by jorgenschaefer** [comment]
Thank you!

**Pull request merged**
