### PR TITLE
Retain point when expanding to indentation

### PR DESCRIPTION
**Pull request by ChillarAnand**
After executing `expand-to-indentation`, if `C-g` is pressed, point
should return to original position

Test is failing, don't know how to  handle `keyboard-quit`.

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
Hm. I can see the use case for this, but I feel very uncomfortable adding a post-command hook just for this. That seems rather excessive for such a minor nuisance. Is this really necessary?

And yes, Emacs does not make it easy to test keyboard interrupt effects. It's probably best to just call `elpy-nav--restore-initial-position` directly there.

**Comment by ChillarAnand** [comment]
> Is this really necessary?

Don't know. Most packages like expand-region, web-mode e.t.c. implement this and i got used to that behaviour.

I think expand-region does this without hooks, if it is simple enough, we can try that.

**Comment by jorgenschaefer** [comment]
Woah :-D https://github.com/magnars/expand-region.el/blob/master/expand-region-core.el#L242-L253

Yeah, better solution, but wow that's ugly. Wouldn't mind a similar implementation if you find that useful.

**Comment by ChillarAnand** [comment]
I know only those solutions. I think it is better to leave elpy as it as for now.

**Pull request closed without merging**
