### PR TITLE
change elpy-rpc-pythonpath to support native-comp

### PR DESCRIPTION
**Pull request by tgbugs**
# PR Summary
The `.eln` files created by the native compile feature are not located in the same folder as the `.el` and `.elc` files they are derived from. This means that using `(locate-library "elpy")` to find the right folder for `elpy-rpc-pythonpath` breaks because it returns something like `"/home/tom/.emacs.d/elpa/elpy-20200527.2021/eln-x86_64-pc-linux-gnu-2ca71878e862259e/"` instead of `"/home/tom/.emacs.d/elpa/elpy-20200527.2021/"`. Using `(locate-library "elpy.el")` instead fixes the issue.

@AndreaCorallo Do you have an idea of the extent to which this will be an issue? In other words, how many codebases make use of `locate-library` in ways that will cause bugs that are similar to this? Probably just something to keep an eye on for the changelog for emacs 28, but might be worth starting some community awareness if it turns out to affect multiple packages.

# PR checklist

Please make sure that the following things have been addressed (and check the relevant checkboxes):

- [x] Commits respect our [guidelines](../CONTRIBUTING.rst)
- [x] Tests are passing properly (see [here](https://elpy.readthedocs.io/en/latest/extending.html#running-tests) on how to run Elpy's tests)

### CODE REVIEW

**Comment by AndreaCorallo** [comment]
Hi,  I'm not really sure but I think most packages use `load-file-name` for that.  

In fact I had to fake its value for compatibility and add `load-true-file-name` to have offer the possibility to obtain the real one.

Not sure if we could or should do something on the `locate-library` side.

**Comment by tgbugs** [comment]
So the suggestion in this context would be to switch to use `(file-name-directory load-file-name)` since that will remain stable. I don't know enough about the decision to use `locate-library` in this context, so will have to wait for further input from one of the maintainers.

**Comment by AndreaCorallo** [comment]
Well, more than a  suggestion was a comment :)

`load-file-name` will keep on pointing to the old directory because otherwise would break to many packages.  

If we think `locate-library` should work differently then what it does now it can certainly be discussed (perhaps on a bug on the Emacs bug tracker).

**Comment by galaunay** [comment]
I am pretty happy with using the `load-file-name` solution in Elpy.
It looks more direct and stable than the `locate-library` alternative.

**Comment by galaunay** [comment]
I took the liberty of modifying your PR following the above discussion.
 Thanks to both of you.

**Pull request merged**
