### PR TITLE
elpy-shell: Non-blocking capturing of output, minor improvements, and bugfixes

### LINKED ISSUE #1205: `elpy-shell-send-statement-and-step` hangs when evaluating time-consuming commands
Hello, 

I find serval spurious changes when I update  elpy to 1.17.0. For example, when I  run command `elpy-shell-send-statement-and-step` , the whole editor will be blockd and I can do nothing until the python shell finish this evaluation.  If I press C-g, it wil send  python shell a `KeyboardInterrupt` and stop the evaluation. 

Besides, `elpy-shell-send-statement-and-step` now seems rely on the  `eval-sexp-fu` package and I have to install it to make elpy-shell commands work.

Thanks!

### PR DESCRIPTION
**Pull request by rgemulla**
Fixes #1205, #1210, #1219. 

Also various smaller improvements in elpy-shell.

### CODE REVIEW

**Comment by rgemulla** [comment]
Not sure why it shows a conflict here. If suffices to cherry-pick 5f20ed5.

**Comment by rgemulla** [comment]
Fixed the issue, now no conflicts anymore.

**Comment by rgemulla** [comment]
I made a few minor "cleanup" changes and improve output echoing. This PR is ready from my point of view.

**Comment by jorgenschaefer** [comment]
Thank you! Do you want to clean up/squash the commits a bit before merging?

**Comment by rgemulla** [comment]
No, it's already well-structured from my point of view.

**Comment by jorgenschaefer** [comment]
Thank you!

**Pull request merged**
