### PR TITLE
Include yapf in elpy config

### PR DESCRIPTION
**Pull request by ChillarAnand**
Added yapf to elpy config.
Key binding(`C-c C-r y`) to call yapf formatter.

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
Thanks for the contribution!

I am currently wondering if it would be better maybe to have one key binding for "fix code formatting", and then use yapf or autopep8 depending on availability? What do you think?

**Comment by ChillarAnand** [comment]
When both are available, which one should we use?

**Comment by jorgenschaefer** [comment]
> When both are available, which one should we use?

I'd say yapf, as it is more featureful.

Do you think there is a (realistic) use case where someone has both autopep8 and yapf installed and would want to run autopep8 instead of yapf?

**Comment by ChillarAnand** [comment]
Yes it is better to make `yapf` default formatter.

Sorry for the delay.

**Comment by jorgenschaefer** [comment]
Thank you!

**Comment by abdulhaq-e** [comment]
This is not included in the latest released version is it?

Thanks.

**Comment by jorgenschaefer** [comment]
I'm afraid it is not, no. It will be in the next release.

**Pull request merged**
