### PR TITLE
Integrated my modifications into current branch

### PR DESCRIPTION
**Pull request by CdeMills**
# PR Summary
A few modifs to make the code running under 24.3

# PR checklist

Please make sure that the following things have been addressed (and check the relevant checkboxes):

- [ ] Commits respect our [guidelines](../CONTRIBUTING.rst)
- [ ] Tests are passing properly (see [here](https://elpy.readthedocs.io/en/latest/extending.html#running-tests) on how to run Elpy's tests)
- [ ] Code is not generating new bytecode warnings

## For new features only:
- [ ] Tests has been added to cover the change
- [ ] The documentation has been updated
- [ ] An entry in NEWS.rst has been added

### CODE REVIEW

**Comment by galaunay** [comment]
You can uncomment Emacs 24.3 in `.travis.yml`.
This way travis will run the test for Emacs 24.3 as well.

**Comment by CdeMills** [comment]
Hello,

I uncommented emacs 24.3 and made a few other changes. Now the set of files
in the pull request compiles
 under Emacs-24.3, but a number of advanced tests fails. No idea why, I
don't know enough of emacs-lisp to figure what's wrong. Could you have a
look ?

Regards

Pascal

**Comment by CdeMills** [comment]
Hello,
1) created a "void" elpy-project-find-projectile-root for emacs <= 25.1, as to not have to mess with lines 155 and 164
2) desactivated the corresponding test in elpy-projectile-find-projectile-root-test.el

The list is now reduced to three failures:
FAILED  elpy-company-backend-should-add-shell-candidates
   FAILED  elpy-shell-kill-should-kill-shell
   FAILED  elpy-shell-kill-should-kill-shell-and-buffer

**Comment by CdeMills** [comment]
Hello,

the first problem is adressed. About the second ... it seems something is missing ? I see the function header and doc, but no body ?

Regards

Pascal

**Comment by CdeMills** [comment]
Hello,
Now there is a conflict on elpy.el and travis build is not starting. How can I solve that ?

Regards

Pascal

**Comment by galaunay** [comment]
I fixed the conflict (and I took the opportunity to fix the remaining problem).
Let see what travis has to say.

**Comment by CdeMills** [comment]
Just one failure with a function which is not supposed to be used -- commented it out

**Comment by galaunay** [comment]
I took the liberty to fix a typo.

**Comment by galaunay** [comment]
I think the best thing to do would be to have a dedicated branch for this.

It will not be on melpa repository, but it will be installable manually, or using [el-get](https://www.emacswiki.org/emacs/el-get) (or any other package manager allowing to fetch from git repos).

This way we don't over-complexify the Elpy's master branch, but people using emacs 24.3 will still be able to use the latest features.

Will this be a good solution for you ?

**Comment by CdeMills** [comment]
Hello,
This option is perfectly fine for me.

Regards

Pascal

**Comment by CdeMills** [comment]
Hello,
I'll test it this evening. Thank you.

Pascal

**Comment by CdeMills** [comment]
Hello,
tested and approved. That's great news !
Thank you

Regards

Pascal

**Pull request closed without merging**
