### PR TITLE
Retain point while autopep8 refactoring

### LINKED ISSUE #660: Could autopep8 leave the cursor where it was?
At the moment elpy-autopep8-fix-code moves the cursor to the beginning of the file after the cleanup is done. Is it possible to change this behaviour to leave the cursor as close as possible to where it was when the function was called?

### PR DESCRIPTION
**Pull request by ChillarAnand**
closes #660 #661

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
- Hm. Retaining point after replacing the whole buffer is tricky. Maybe rather store line number and column or something?
- Please use `when` instead of `if` if you have no alternative branch. :-)

**Comment by ChillarAnand** [comment]
> Hm. Retaining point after replacing the whole buffer is tricky. Maybe rather store line number and column or something?

autopep8 does whitespace cleanup, there is no gaurantee that saved line/column will even exist after cleanup.

> Please use when instead of if if you have no alternative branch. :-)

Roger that :-)

**Comment by jorgenschaefer** [comment]
Applied the partially selected line fix. Thank you, excellent work! I'm especially happy for the tests! :-)

> autopep8 does whitespace cleanup, there is no gaurantee that saved line/column will even exist after cleanup.

Nor is there a guarantee that the saved byte offset into the buffer will exist, which is what your patch is adding. Both are heuristics and guesswork. The question is, which one will work better in most cases?

Using the byte offset means that even small changes will cause point to move around. Line and column might be less confusing for users.

A user on `#emacs-elpy` mentioned that `py-autopep8.el` is able to retain cursor position more accurately than Elpy. Any idea how it does this?

**Comment by ChillarAnand** [comment]
Yes, yes. It is much better to restore line/column positions. py-autopep8 is also doing same thing. Updated it. :-)

**Comment by jorgenschaefer** [comment]
Excellent, thank you!

**Pull request merged**
