### PR TITLE
avoid "Unused lexical argument" warnings

### PR DESCRIPTION
**Pull request by sam-s**

### CODE REVIEW

**Comment by rgemulla** [comment]
I find it somewhat unsatisfying to change outside visible variable names to get rid of byte compile warnings. But I have no strong option either way.

**Comment by gopar** [comment]
Seems this is somewhat common: https://github.com/bbatsov/emacs-lisp-style-guide#naming

**Comment by galaunay** [comment]
I though several times about trying to reduce compilation warning number, 
thank you for having the courage to actually do it.

I think this is a valuable information to know which parameter as a real influence on the function,
I am voting in favor of this.

**Comment by gopar** [comment]
Has my vote. It can be merged.

**Pull request merged**
