### PR TITLE
Add function to select surrounding lines with current indentation

### LINKED ISSUE #616: Select surrounding lines with same indentation
As a user, I want to be able to select all surrounding lines with the same indentation as the current one, in order to manipulate this region (e.g. changing indentation).

Sublime apparently calls this "expand to indentation" and binds it to `C-S-j`

### PR DESCRIPTION
**Pull request by ChillarAnand**
Not sure which key binding to use for this. Suggestions?

closes #616

### CODE REVIEW

**Comment by jorgenschaefer** [comment]
Thank you for this work!

I think #616 actually means "same or deeper indentation", so you shouldn't use `eq` but rather something like `<=` for your checks (in general, don't use `eq` for numbers, just use `=` or at least `eql`; there is no guarantee that two identical numbers are `eq` if Emacs ever gets bignums, like XEmacs has).

Also please note that `previous-line` and `next-line` say specifically _"This function is for interactive use only"_, so please use `forward-line` as advised there. The correct way of marking and highlighting a region from Emacs Lisp is to use `set-mark` and `activate-mark`, or `push-mark` with the `ACTIVATE` argument set to `t`, so something like this:

```Lisp
(goto-char end)
(push-mark beg nil t)
```

You can try writing a test for this, too, if you like, but that can be tricky :-)

**Comment by ChillarAnand** [comment]
My bad. Lots of mistakes!

Updated function & added a test case.

**Comment by jorgenschaefer** [comment]
Wow, very nice! This looks good.

The key binding `C-c C-j` is used by python.el already. What do you think about `C-c C-b` for "block"?

Other than that, I'm happy to merge this – could you squash the commits into a single one?

Thank you!

**Comment by ChillarAnand** [comment]
Done!

**Comment by jorgenschaefer** [comment]
Excellent. Thank you very much for your work! :-)

**Pull request merged**
