### PR TITLE
Add support for python3.7

### PR DESCRIPTION
**Pull request by galaunay**
# PR Summary
Add travis tests for python3.7.

### CODE REVIEW

**Comment by galaunay** [comment]
We will have to wait a bit for travis to support properly python3.7.
See Travis issue [#9815](https://github.com/travis-ci/travis-ci/issues/9815).

**Comment by galaunay** [comment]
At this time, travis still not support for python3.7...

**Comment by gopar** [comment]
Looks like there is an official workaround to get 3.7 up and running:
https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905

**Comment by gopar** [comment]
Looks like everything passes except for the company test, which shouldn't of been affected by this

**Comment by galaunay** [comment]
Sorry I kind of left this on the side because I couldn't get my head around the travis configuration file.
At the moment it is not running all the wanted tests configurations.

I made another try, let's see...

**Comment by galaunay** [comment]
Alright, this is doing what I want now (ugly but efficient...).

Let see if we still have issues with Company.

**Comment by galaunay** [comment]
A script we are using during travis installation broke (nothing related to this PR apparently).

I fixed it as well and will try to merge it as soon as possible to avoid the tests failing on the main branch...

**Comment by gopar** [comment]
Ooops, sorry.
I realized that the comment had a 'mean' tone to it :P 
I was mostly writing down my thoughts on the failing tests, sorry about that 😨

**Comment by galaunay** [comment]
@gopar Don't worry, I got that :).

**Pull request merged**
